.pc

.TH MAN 1 "2013-04-24" "1.x-git" "Slider"

.SH NAME
slider \- pdf presentation tools


.SH SYNOPSIS
.B slider
.RB [\| \-c \|]
.RB [\| \-a \|\c
.RI N \|]
.RB [\| \-s \|\c
.IR N \|]
.RB [\| \-p \|\c
.IR N \|]
.RB [\| \-m \|\c
.IR VID1 \c
,\c
.IR VID2 \|]
.RB [\| \-g \|\c
.IR WxH+X+Y
\|[\|.\|.\|.\|]\|]
.IR presentation.pdf
\|[\c
.IR notes.pdf \c
\|]

.SH DESCRIPTION
TODO

.SH OPTIONS
.TP
.BI \-c
Continuous loop mode.  When the presentation finishes, it will loop back to the first slide.
.TP
.BI \-a \|N
Autoplay mode.  Slides will advance automatically at intervals of
.I N
seconds.  If
.I N
is not specified, a default of 10 seconds is used.
.TP
.BI \-s \|N
Scales the primary view in presenter mode to
.I N
times larger than secondary view (default=1.8).  This option is ignored if you specify any geometry strings.  Suitable values depend on monitor aspect ratio, but can range from 1.75-3 for presentations with separate notes, or 0.5-3 for presentations alone.
.TP
.BI \-p \|N
Prerenders
.I N
slides (default=2).  Rendering proceeds faster if the presentation is
"prerendered", but then you have to wait for it to complete before
interacting with slider.  For very large presentations, it may be useful
to prerender many/all slides.  If
.I N
is anything other than a positive integer, all slides are prerendered.
.TP
.BI \-m \|VID1
.TP
.BI \-m \|VID1,VID2
Overrides the default monitor detection and sends the presentation to the
video output named VID1.  The first form disable presenter mode notes.  The
second form sends the presentation to VID1 and the notes to VID2.
.TP
.BI \-g \|WxH+X+Y
Geometry strings for view panes in presenter mode.  Set the width, height, and locations of up to 4 presenter mode panels.  Panels display the following items
on the presenter monitor:

.TS
lb lb lb
l l l
l l l
l l l
l l l.
PANEL	NOTES	NO NOTES
1	Notes	Current Slide
2	Current Slide	Next Slide
3	Next Slide	Previous Slide
4	Previous Slide	NA
.TE


.SH EXAMPLES
TODO


.SH CONTROLS
TODO


.SH AUTHOR / COPYRIGHT / BUGS
Copyright\(co 2012-2013 Jesse McClure.
.br
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Report bugs through <http://github.com/TrilbyWhite/Slider.git>


